MVC/Controllers/ReadingsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataAccess.Contexts;
using DataAccess.Entities;
using Business.Services;
using Business;
using Business.Models;
using Microsoft.AspNetCore.Authorization;

namespace MVC.Controllers
{
    [Authorize]
    public class ReadingsController : Controller
    {
        private readonly IReadingService _readingService;
        private readonly IUserService _userService;
        private readonly IRoleService _roleService;

        public ReadingsController(IReadingService readingService, IUserService userService, IRoleService roleService)
        {
            _readingService = readingService;
        }
        #region User and Role Service Constructor Injections


        #endregion


        public IActionResult Index(int id)
        {
            List<ReadingModel> readingList = _readingService.GetList();
            return View(readingList);
        }
        public IActionResult Details(int id)
        {
            ReadingModel reading = _readingService.GetItem(id);
            if (reading == null)
            {
                return NotFound();
            }
            return View(reading);
        }

        public IActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ReadingModel reading)
        {
            if (ModelState.IsValid)
            {
                var result = _readingService.Add(reading);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Message);
            }

            return View(reading);
        }
        public IActionResult Edit(int id)
        {
            ReadingModel reading = _readingService.Query().SingleOrDefault(r => r.Id == id);
            if (reading == null)
            {
                return NotFound();
            }
        
            return View(reading);
        }

        [Authorize(Roles = "admin,readr")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ReadingModel reading)
        {
            if (ModelState.IsValid)
            {
                var result = _readingService.Update(reading);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Message);
            }

            return View(reading);
        }
        public IActionResult Delete(int id)
        {
            ReadingModel reading = _readingService.Query().SingleOrDefault(r => r.Id == id);
            if (reading == null)
            {
                return NotFound();
            }
            return View(reading);
        }

        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var result = _readingService.Delete(id);
            TempData["Message"] = result.Message;
            return RedirectToAction(nameof(Index));
        }
	}
}

MVC/Controllers/RolesController.cs
#nullable disable
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVC.Controllers.Bases;

namespace MVC.Controllers
{
    [Authorize(Roles = "admin")]
    public class RolesController : MvcControllerBase 
    {

        private readonly IRoleService _roleService;

        public RolesController(IRoleService roleService)
        {
            _roleService = roleService;
        }

        public IActionResult Index()
        {
            List<RoleModel> roleList = _roleService.Query().ToList();
            return View(roleList);
        }

        public IActionResult Details(int id)
        {
            RoleModel role = _roleService.Query().SingleOrDefault(r => r.Id == id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        public IActionResult Create()
        {
         
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RoleModel role)
        {
            if (ModelState.IsValid)
            {
                var result = _roleService.Add(role);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Message);
            }
            
            return View(role);
        }

       
        public IActionResult Edit(int id)
        {
            RoleModel role = _roleService.Query().SingleOrDefault(r => r.Id == id);
            if (role == null)
            {
                return NotFound();
            }
            
            return View(role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(RoleModel role)
        {
            if (ModelState.IsValid)
            {
                var result = _roleService.Update(role);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Message);
            }
            
            return View(role);
        }

        
        public IActionResult Delete(int id)
        {
            var result = _roleService.Delete(id);
            TempData["Message"] = result.Message;
            return RedirectToAction(nameof(Index));
        }
	}
}

MVC/Controllers/UsersController.cs
#nullable disable
using Business;
using Business.Models;
using DataAccess.Results.Bases;
using Business.Services;
using DataAccess.Enums;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;
using MVC.Controllers.Bases;

namespace MVC.Controllers
{
    public class UsersController : MvcControllerBase
    {
        #region User and Role Service Constructor Injections
        private readonly IUserService _userService;
        private readonly IRoleService _roleService;

		public UsersController(IUserService userService, IRoleService roleService)
		{
			_userService = userService;
			_roleService = roleService;
		}
        #endregion

        [Authorize]
        public IActionResult GetList()
        {
            List<UserModel> userList = _userService.Query().ToList();


            return View("List", userList);
        }

        [Authorize(Roles = "admin")]
        public JsonResult GetListJson()
        {
            var userList = _userService.Query().ToList();
            return Json(userList);
        }

        [Authorize(Roles = "admin")]
        public IActionResult Details(int id)
        {
            UserModel user = _userService.Query().SingleOrDefault(u => u.Id == id);

            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            ViewBag.Roles = new SelectList(_roleService.Query().ToList(), "Id", "Name");

			return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public IActionResult Create(UserModel user)
        {
            if (ModelState.IsValid)
            {
                Result result = _userService.Add(user);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(GetList));
                }

				ModelState.AddModelError("", result.Message); 

            }

			ViewBag.Roles = new SelectList(_roleService.Query().ToList(), "Id", "Name");
			return View(user); 
        }

        [Authorize(Roles = "admin")]
        public IActionResult Edit(int id)
        {
            UserModel user = _userService.Query().SingleOrDefault(u => u.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            ViewBag.RoleId = new SelectList(_roleService.Query().ToList(), "Id", "Name");
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public IActionResult Edit(UserModel user)
        {
            if (ModelState.IsValid)
            {
                var result = _userService.Update(user);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(GetList));
                }
                ModelState.AddModelError("", result.Message);
            }
            
            ViewBag.RoleId = new SelectList(_roleService.Query().ToList(), "Id", "Name");
            return View(user);
        }

        [Authorize(Roles = "admin")]
        public IActionResult Delete(int id)
        {
            UserModel user = _userService.Query().SingleOrDefault(u => u.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

		[HttpPost, ActionName("Delete"), ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public IActionResult DeleteConfirmed(int id)
        {
            var result = _userService.DeleteUser(id);
			
            TempData["Message"] = result.Message;
			 
            return RedirectToAction(nameof(GetList));
        }
    }
}

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @AppSettings.AppTitle</title> @* titles set in the views will be written here by ViewData["Title"] *@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">

                <a class="navbar-brand layoutheader" asp-area="" asp-controller="Home" asp-action="Index">@AppSettings.AppTitle</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Readings" asp-action="Index">Tarot Falların</a>
                            </li>

                        }

			            @* 
			            *@
                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Role List</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="GetList">User List</a>
                            </li>
                        }

                    </ul>

                    <div class="navbar-text">
                        <ul class="navbar-nav me-auto">
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">

                                    <a class="nav-link text-dark" asp-area="Account" asp-controller="Home" asp-action="Login">Login</a>

                                </li>
                                <li class="nav-item">

                                    <a class="nav-link text-dark" asp-area="Account" asp-controller="Home" asp-action="Register">Register</a>

                                </li>
                            }
                            else
                            {
                                <li class="nav-item pt-2">
                                    <span class="badge bg-info text-black">@User.Identity.Name</span>
                                </li>
                                @:&nbsp;&nbsp;

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Account" asp-controller="Home" asp-action="Logout">Logout</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            
            &copy; @DateTime.Now.Year - TarotLife

        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>